spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:

  flyway:
    enabled: false

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
