spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/damda?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: root
    password: damda

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
